/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyFrameWork;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedCondition;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;


public class LibraryTest {
WebDriver driver;
WebDriverWait wait;
	
	@BeforeTest
	public void fnNavigatetoGoogle()
	{
		System.setProperty("webdriver.chrome.driver", "C:\\Users\\Sundaresh\\eclipse-workspace\\JPRFrame\\src\\test\\resources\\chromedriver_win32\\chromedriver.exe");
		driver = new ChromeDriver();
		driver.get("https://ci-qa.augustasoftsol.com/#/main-home");
		 wait = new WebDriverWait(driver, 50000); 
	}
	
	@Test(priority=1)
	public void fnLogin() throws InterruptedException
	{
		Thread.sleep(5000);
		 wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//a[text()='LOGIN']")));
		 driver.findElement(By.xpath("//a[text()='LOGIN']")).click();
		 wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//input[@placeholder='Username']")));
//		 wait.until(ExpectedConditions.elementToBeClickable(driver.findElement(By.xpath("//input[@placeholder='Username']"))));
		 driver.findElement(By.xpath("//input[@placeholder='Username']")).sendKeys("jothi");
		 driver.findElement(By.xpath("//input[@placeholder='Password']")).sendKeys("Augusta@12");
		 driver.findElement(By.xpath("//span[contains(text(),'LOG IN')]")).click();
		 Thread.sleep(5000);
		 Assert.assertTrue(driver.getCurrentUrl().contains("home"));
		 wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//span[@class='button-inner']")));
		 Assert.assertTrue(driver.findElement(By.xpath("//span[@class='button-inner']")).isDisplayed());
		 		 
	}
	
	@Test(priority=2)
	public void fnNavigateToSettings() throws InterruptedException
	{
		driver.findElement(By.xpath("//span[@class='button-inner']")).click();
		wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//label[text()='Settings']")));
		driver.findElement(By.xpath("//label[text()='Settings']/parent::node()/parent::node()")).click();
		Thread.sleep(5000);
		Assert.assertTrue(driver.getCurrentUrl().contains("settings"));
		//driver.findElement(By.xpath("//span[text()='Okay']")).click();
		//Assert.assertTrue(driver.findElement(By.id("public")).getAttribute("ng-reflect-ng-class").equalsIgnoreCase("tab-active"));
	}
	
	@Test(priority=3)
	public void fnAddNewGroup() throws InterruptedException
	{
		
		driver.findElement(By.xpath("//label[text()='Groups']/parent::node()")).click();
		driver.findElement(By.xpath("//label[text()='Add Group']/parent::node()")).click();
		

		
		
		
		
		
		
		//item item-block item-md item-input ng-untouched ng-pristine ng-invalid
		
		driver.findElement(By.xpath("//ion-icon[@name='add']/parent::node()/parent::node()")).click();
		driver.findElement(By.xpath("//input[@placeholder='Name']")).sendKeys("New Skin of 1");
		driver.findElement(By.xpath("//textarea[@placeholder='Description']")).sendKeys("New Skin of 1 Description");
		WebElement question= driver.findElement(By.xpath("//ion-input[@placeholder='Question']"));
		new Actions(driver).moveToElement(question).perform();

		//String classname= question.getAttribute("class");
		//String updateclassname = classname+" input-has-focus item-input-has-focus";
		//JavascriptExecutor js = (JavascriptExecutor) driver;
		//js.executeScript("document.getElementsByClassName('"+classname+"').setAttribute('class','"+updateclassname+"')");
		//js.executeScript("arguments[0].setAttribute('class','"+updateclassname+"')");
		driver.findElement(By.xpath("//ion-input[@placeholder='Question']")).sendKeys("Any Info");
		driver.findElement(By.xpath("//span[contains(text(),'SAVE')]")).click();
		Assert.assertTrue(driver.findElement(By.xpath("//div[@class='toast-message']")).getText().contains("success"));
		Thread.sleep(5000);
		Assert.assertTrue(driver.findElement(By.id("private")).getAttribute("ng-reflect-ng-class").equalsIgnoreCase("tab-active"));
	}
	
	@AfterTest
	public void fnClose()
	{
		driver.quit();
	}
	


}
